# Generated by Django 3.2.4 on 2024-05-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(),
        ),
    ]
