# Generated by Django 3.2.4 on 2024-05-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
