# Generated by Django 3.2.4 on 2024-05-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_question_text_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='classification',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='chilled', max_length=10),
        ),
    ]
