# Generated by Django 3.2.4 on 2024-05-14 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 7, 14, 9, 58140, tzinfo=utc)),
        ),
    ]
